// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	user "tiktok/kitex_gen/user"
)

func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

var userServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Register":    kitex.NewMethodInfo(registerHandler, newUserServiceRegisterArgs, newUserServiceRegisterResult, false),
		"Signin":      kitex.NewMethodInfo(signinHandler, newUserServiceSigninArgs, newUserServiceSigninResult, false),
		"GetUserById": kitex.NewMethodInfo(getUserByIdHandler, newUserServiceGetUserByIdArgs, newUserServiceGetUserByIdResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRegisterArgs)
	realResult := result.(*user.UserServiceRegisterResult)
	success, err := handler.(user.UserService).Register(ctx, realArg.ServiceReqRegister)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return user.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return user.NewUserServiceRegisterResult()
}

func signinHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceSigninArgs)
	realResult := result.(*user.UserServiceSigninResult)
	success, err := handler.(user.UserService).Signin(ctx, realArg.ServiceReqSignin)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceSigninArgs() interface{} {
	return user.NewUserServiceSigninArgs()
}

func newUserServiceSigninResult() interface{} {
	return user.NewUserServiceSigninResult()
}

func getUserByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUserByIdArgs)
	realResult := result.(*user.UserServiceGetUserByIdResult)
	success, err := handler.(user.UserService).GetUserById(ctx, realArg.ServiceReqGetUserById)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserByIdArgs() interface{} {
	return user.NewUserServiceGetUserByIdArgs()
}

func newUserServiceGetUserByIdResult() interface{} {
	return user.NewUserServiceGetUserByIdResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, serviceReqRegister *user.ServiceReqRegister) (r *user.ServiceResRegister, err error) {
	var _args user.UserServiceRegisterArgs
	_args.ServiceReqRegister = serviceReqRegister
	var _result user.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Signin(ctx context.Context, serviceReqSignin *user.ServiceReqSignin) (r *user.ServiceResSignin, err error) {
	var _args user.UserServiceSigninArgs
	_args.ServiceReqSignin = serviceReqSignin
	var _result user.UserServiceSigninResult
	if err = p.c.Call(ctx, "Signin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserById(ctx context.Context, serviceReqGetUserById *user.ServiceReqGetUserById) (r *user.ServiceResGetUserById, err error) {
	var _args user.UserServiceGetUserByIdArgs
	_args.ServiceReqGetUserById = serviceReqGetUserById
	var _result user.UserServiceGetUserByIdResult
	if err = p.c.Call(ctx, "GetUserById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
