debug: true
sql_debug: false

app:
  addr: ":3000"
  prefix: "tiktok"
  timeformat: "2006-01-02 15:04:05"
redis:
  addr: "redis:6379"
  password: "password"
  db: 0
db:
  addr: "27017"
  db: "tiktok"
  username: "root"
  password: "password"
  timeout_second: 5
jwt:
  secret: "eu2iw8sa"
logConf:
  log_path: "log"
  log_file_name: "log"

